FROM mysql:8.0.2
#FROM mysql:mysql-server
#RUN apt-get update; 
#RUN apt-get --fix-missing;
#RUN apt-get upgrade -f -y --force-yes;
COPY database.sql /home/database.sql
#RUN mysql -u root -p password < /home/database.sql
